version: '3'
services:
  app:
    build: ./
    image: local/api-6-semestre:dev
    pull_policy: never
    volumes:
      - .:/api-6-semestre
    ports:
      - "5005:5000"
    env_file:
      - .env
    command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=5000 --debug"
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5440:5432"
