services:
  app:
    build: ./
    image: local/api-6-semestre:dev
    pull_policy: never
    volumes:
      - .:/api-6-semestre
    ports:
      - "5005:5000"
    env_file:
      - .env
    command: bash -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=5000 --debug"
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_started

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

volumes:
  mongodb_data:
