version: '3'
services:
  app:
    build: ./
    image: local/api-6-semestre:dev
    pull_policy: never
    volumes:
      - .:/api-6-semestre
    ports:
      - "5005:5000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      DB_ADDR: postgres
      DB_NAME: database
      DB_USER: postgres
      DB_PASSWORD: postgres
    command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=5000 --debug"
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5440:5432"

