name: Build for main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Define repository name in lowercase
      run: echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Test
      run: echo "FLAG_VERSION=$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Test repository name
      run: echo "The repository is ${{ env.REPOSITORY_NAME }}"

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ env.REPOSITORY_NAME }}/server:latest .

    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ env.REPOSITORY_NAME }}/server:latest
